#define FALSE 0
#define TRUE 1
#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 800
#define BLOCK_WIDTH 25
#define BLOCK_HEIGHT 25
#define FONT "./fonts/BodoniFLF-Roman.ttf"
#define FONT_SIZE 20
#define TEXT_COLOR_RGBA 255, 255, 0, 255 
#define RUNNING TRUE
#define PAUSED FALSE
#define FPS_PAUSED 60
#define FPS_RUNNING 20
#define PAUSED_FRAME_TARGET_TIME (100/FPS_PAUSED)
#define RUNNING_FRAME_TARGET_TIME (100/FPS_PAUSED)